/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src\Models\Table\Table.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Table.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Table_top.geometry} material={nodes.Table_top.material} />
      <mesh geometry={nodes.Leg.geometry} material={nodes.Leg.material} position={[0, 0.12, 0]} />
      <mesh geometry={nodes.Leg002.geometry} material={nodes.Leg002.material} position={[0, 0.12, 0]} />
      <mesh geometry={nodes.Leg003.geometry} material={nodes.Leg003.material} position={[0, 0.12, 0]} />
      <mesh geometry={nodes.Leg004.geometry} material={nodes.Leg004.material} position={[0, 0.12, 0]} />
      <mesh geometry={nodes.Leg006.geometry} material={nodes.Leg006.material} position={[0, 0.12, 0]} />
    </group>
  )
}

useGLTF.preload('/Table.gltf')
