/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src\Models\Table_type_02.gltf --transform 
Files: src\Models\Table_type_02.gltf [6.9KB] > C:\Programing\Final_project\Table_type_02-transformed.glb [11.06KB] (-60%)
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useCustomization } from '../context/Customization'


const Table_type_02 = (props) => {
  const { nodes, materials } = useGLTF('./src/Models/Table_type_02.gltf')
  const {material ,tableWidth,tableDepth,tableHeight,} = useCustomization()

  const tableWidthScale = tableWidth / 200 
  const tableDepthScale = tableDepth / 100 
  const tableHeightScale = tableHeight /100


  const dub = useTexture({
    map: './src/Textures/Oak_wood/Wood_025_basecolor.jpg',
    normalMap: './src/Textures/Oak_wood/Wood_025_normal.jpg',
    roughnessMap: 'src/Textures/Oak_wood/Wood_025_roughness.jpg',
    aoMap: './src/Textures/Oak_wood/Wood_025_ambientOcclusion.jpg',
  })
  const borovice = useTexture({
    map: './src/Textures/Pine_wood/Wood_Plywood_Front_001_basecolor.jpg',
    normalMap: './src/Textures/Pine_wood/Wood_Plywood_Front_001_normal.jpg',
    roughnessMap: 'src/Textures/Pine_wood/Wood_Plywood_Front_001_roughness.jpg',
    aoMap: './src/Textures/Pine_wood/Wood_Plywood_Front_001_ambientOcclusion.jpg',
  })
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} 
            material={materials.Material} />

      <mesh geometry={nodes.Plane.geometry} 
            material={materials['Material.001']} 
            position={[0.628, 1.042, 0.022]} 
            rotation={[-2.602, -0.949, -2.689]} />

      <mesh geometry={nodes.Plane001.geometry} 
            material={materials['Material.003']} 
            position={[-0.304, 0.636, 1.069]} 
            rotation={[0, 1.157, -2.134]} />

      <mesh geometry={nodes.Plane002.geometry} 
            material={materials['Material.002']} 
            position={[-1.343, 0, -2.054]} 
            rotation={[0, 0.459, 0]} />
    </group>
  )
}

useGLTF.preload('/Table_type_02-transformed.glb')

export default Table_type_02