/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/Models/Table_type_01.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'
import * as THREE from "three"


const Table_type_01 = (props) => {
  const { nodes, materials } = useGLTF('src/Models/Table_type_01.gltf')
  const woodTextureProps = useTexture({
    map: './src/Textures/Oak_wood/Wood_025_basecolor.jpg',
    normalMap: './src/Textures/Oak_wood/Wood_025_normal.jpg',
    roughnessMap: 'src/Textures/Oak_wood/Wood_025_roughness.jpg',
    aoMap: './src/Textures/Oak_wood/Wood_025_ambientOcclusion.jpg',
  })
  
woodTextureProps.map.repeat.set(7,7)
woodTextureProps.normalMap.repeat.set(5,5)
woodTextureProps.roughnessMap.repeat.set(2,2)
woodTextureProps.aoMap.repeat.set(2,2)

woodTextureProps.map.wrapS = woodTextureProps.map.wrapT = 
woodTextureProps.normalMap.wrapS = woodTextureProps.normalMap.wrapT = 
woodTextureProps.roughnessMap.wrapS = woodTextureProps.roughnessMap.wrapT = 
woodTextureProps.aoMap.wrapS = woodTextureProps.aoMap.wrapT = 

THREE.RepeatWrapping

  
  return (
    
    <group {...props} dispose={null}>
      
      <mesh

        geometry={nodes.Desk.geometry} 
        material={nodes.Desk.material} 
        position={[0.008, 0.752, -0.12]} 
        rotation={[-0.001, 0.035, -0.002]}
        scale={[1,1,1]} >
            <meshStandardMaterial {...woodTextureProps}/>

      </mesh>
      <mesh 
        geometry={nodes.Leg1.geometry} 
        material={nodes.Leg1.material} 
        position={[0.885, 0.086, 0.205]} 
        rotation={[3.141, -0.035, -3.14]} 
        scale={[-1, -1.008, -1]} >
            <meshStandardMaterial {...woodTextureProps}/>
      </mesh>
      <mesh 
        geometry={nodes.Leg2.geometry} 
        material={nodes.Leg2.material} 
        position={[0.86, 0.085, -0.493]} 
        rotation={[3.141, -0.035, -3.14]} 
        scale={[-1, -1.008, -1]} >
          <meshStandardMaterial {...woodTextureProps}/>
      </mesh>
      <mesh 
        geometry={nodes.Leg3.geometry} 
        material={nodes.Leg3.material} 
        position={[-0.855, 0.089, 0.266]} 
        rotation={[-0.001, 0.035, 3.14]} scale={[1, 1.008, 1]} >
          <meshStandardMaterial {...woodTextureProps}/>
      </mesh>
      <mesh 
        geometry={nodes.Leg4.geometry} 
        material={nodes.Leg4.material} 
        position={[-0.88, 0.088, -0.432]} 
        rotation={[3.141, -0.035, -3.14]} 
        scale={[-1, -1.008, -1]} >
          <meshStandardMaterial {...woodTextureProps}/>
          
      </mesh>
    </group>
  )
}

useGLTF.preload('src/Models/Table_type_01.gltf')

export default Table_type_01